destination: a
highlighter: rouge
markdown: kramdown
name: javisantana.com
description: Pixels are the humble bricks with which one can build cathedrals
url: http://javisantana.com
plugins: [jekyll-paginate]

paginate: 5
paginate_path: "/blog/page:num/"

prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog3"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         "studio"
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         "micro-book-template"
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

collections:
    smalldata:
        output: true
